2021-04-06 10:03:42,099 ERROR: Exception on /login [GET] [in c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\routes.py", line 53, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\templates\base.html", line 37, in block "content"
    {% block content %}
jinja2.exceptions.UndefinedError: 'get_flashed_message' is undefined
2021-04-06 10:03:47,516 ERROR: Exception on /favicon.ico [GET] [in c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\vo xuan anh\desktop\flask_tut\flask_mega_tutorial\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\templates\base.html", line 37, in block "content"
    {% block content %}
jinja2.exceptions.UndefinedError: 'get_flashed_message' is undefined
2021-04-06 10:04:56,567 INFO: Microblog startup [in C:\Users\Vo Xuan Anh\Desktop\flask_tut\flask_mega_tutorial\app\__init__.py:59]
2021-04-18 21:44:11,292 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:63]
2021-04-18 21:52:49,232 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:63]
2021-04-18 23:44:39,243 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:54]
2021-04-18 23:46:43,749 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:54]
2021-04-18 23:47:04,305 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:54]
2021-04-18 23:47:14,501 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:54]
2021-04-19 00:15:08,345 INFO: Microblog startup [in I:\study\workspace\flask\flask_mega_tutorial\app\__init__.py:54]
